# Generated by Django 6.0.3 on 2026-07-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        default="Kontur",
                        max_length=255,
                        verbose_name="Название приложения",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#F3EFE6", max_length=7, verbose_name="Основной цвет"
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#1B2A6B", max_length=7, verbose_name="Вторичный цвет"
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#7FE0F5",
                        max_length=7,
                        verbose_name="Дополнительный цвет",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройки приложения",
                "verbose_name_plural": "Настройки приложения",
            },
        ),
    ]
